def triangular(n):
	return n*(n+1)/2
def square(n):
	return n*n
def pentagonal(n):
	return n*(3*n-1)/2
def hexagonal(n):
	return n*(2*n-1)
def heptagonal(n):
	return n*(5*n-3)/2
def octagonal(n):
	return n*(3*n-2)
